# Steps in Data preprocessing
1. import the data
2. clean the data
3. spilt data into training and test sets

# Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Reading the Data From dataset

In [2]:
data =pd.read_csv("Data.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In a Dataset we have two features and dependent variable vectors
1. Features are the column which are used to predict the dependent variables or the output.They are also called indepnedent variables who predict the dependent variables Ex: in above Age and salary
2. Dependent variables are what is predicted or the output. Ex purchased

# Taking the two entities 

In [3]:
X = data.iloc[:,:3].values #iloc is location of indexes first set is row second is column
Y=data.iloc[:,3].values
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

We have missing data in germany 40.0 so lets take care of that

In [4]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


# Imputer
this is what is used to fill and take care of missing data
here the missing_values represent what kind of evalue to fill in this case nan and the strategy is mean of values

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
print(X[:,1:]) # old
imputer.fit(X[:,1:])
X[:,1:]=imputer.transform(X[:,1:])
print("\n",X[:,1:]) # new

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]

 [[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


# Encoding The Categorical data
the dataset contains numerical data -age and salary
categorical data - country and Y

thus this needs to be converted into numerical data

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Difference between OnehotEncoding and LabelEncoding
LabelEncoding - converts data into labels depending on the number of data for ex if there is Yes and No output it will have 0 and 1 thus
it establishes a specific relation between rows

OneHotEncoding -  converts a specific column into n seprate columns depending on the the number of values these columns will have specifically values 
0 and 1 depending on the data being used

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the data

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)
print(Y_train,Y_test)

[0 1 0 0 1 1 0 1] [0 1]


# Feature Scaling
It is done so that some features do not dominate other features


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
